name: Build Windows EXE

on:
  push:
    branches: [main] # Change "main" if your branch is named differently
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE with PyInstaller
        run: pyinstaller --onefile --name "beneath_her_song" project_files/main.py

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/MyGame.exe
